"""from_sql_lab field

Revision ID: 2863a0ab51af
Revises: 1cea9ca185b2
Create Date: 2021-07-29 07:40:39.763066

"""

# revision identifiers, used by Alembic.
revision = '2863a0ab51af'
down_revision = '1cea9ca185b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.add_column('tables', sa.Column('from_sql_lab', sa.Boolean(), nullable=True))
    conn = op.get_bind()
    conn.execute("UPDATE tables set from_sql_lab=True WHERE sql is not null")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'from_sql_lab')
    # ### end Alembic commands ###
