"""empty message

Revision ID: 2ad905892e34
Revises: 28e1974b81a4
Create Date: 2018-04-12 11:10:07.355600

"""

# revision identifiers, used by Alembic.
revision = '2ad905892e34'
down_revision = '28e1974b81a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'slices_table_id_fkey', 'slices', type_='foreignkey')
    op.drop_constraint(u'slices_druid_datasource_id_fkey', 'slices', type_='foreignkey')
    op.drop_column('slices', 'druid_datasource_id')
    op.drop_column('slices', 'table_id')
    op.create_unique_constraint(None, 'sql_metrics', ['table_id', 'metric_name'])
    op.create_unique_constraint(None, 'table_columns', ['table_id', 'column_name'])
    op.drop_constraint(u'_customer_location_uc', 'tables', type_='unique')
    op.create_unique_constraint(None, 'tables', ['database_id', 'table_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='unique')
    op.create_unique_constraint(u'_customer_location_uc', 'tables', ['database_id', 'schema', 'table_name'])
    op.drop_constraint(None, 'table_columns', type_='unique')
    op.drop_constraint(None, 'sql_metrics', type_='unique')
    op.add_column('slices', sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('slices', sa.Column('druid_datasource_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'slices_druid_datasource_id_fkey', 'slices', 'datasources', ['druid_datasource_id'], ['id'])
    op.create_foreign_key(u'slices_table_id_fkey', 'slices', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###
