"""empty message

Revision ID: 373ad5861835
Revises: bacbfb874d8d
Create Date: 2020-10-27 14:13:16.995588

"""

# revision identifiers, used by Alembic.
revision = '373ad5861835'
down_revision = 'bacbfb874d8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['dashboard_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dashboards', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dashboards', 'dashboard_folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dashboards', type_='foreignkey')
    op.drop_column('dashboards', 'folder_id')
    op.drop_table('dashboard_folders')
    # ### end Alembic commands ###
