"""empty message

Revision ID: 695a531fb67f
Revises: c7d301afb8bc
Create Date: 2020-05-27 19:14:49.859741

"""

# revision identifiers, used by Alembic.
revision = '695a531fb67f'
down_revision = 'c7d301afb8bc'

from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - ADJUSTED ###
    op.alter_column('table_columns', 'auto_upd_verbose_name', existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - ADJUSTED ###
    op.alter_column('table_columns', 'auto_upd_verbose_name', existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###
