"""empty message

Revision ID: 6f442fa5e6dd
Revises: 3761cc38ad6c
Create Date: 2020-05-24 13:57:17.621801

"""

# revision identifiers, used by Alembic.
revision = '6f442fa5e6dd'
down_revision = '3761cc38ad6c'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - ADJUSTED ###
    op.create_table('change_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('action', sa.String(length=16), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('user_name', sa.String(length=64), nullable=False),
        sa.Column('user_roles', sa.String(length=512), nullable=False),
        sa.Column('table_id', sa.Integer(), nullable=True),
        sa.Column('table_name', sa.String(length=512), nullable=False),
        sa.Column('obj_type', sa.String(length=32), nullable=False),
        sa.Column('obj_name', sa.String(length=512), nullable=False),
        sa.Column('obj_field', sa.String(length=32), nullable=False),
        sa.Column('old_value', sa.Text(), nullable=True),
        sa.Column('new_value', sa.Text(), nullable=True),
        sa.Column('dttm', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - ADJUSTED ###
    op.drop_table('change_logs')
    # ### end Alembic commands ###
