"""empty message

Revision ID: 95e3e8796193
Revises: 0008074a556d
Create Date: 2017-05-29 15:10:23.314109

"""

# revision identifiers, used by Alembic.
revision = '95e3e8796193'
down_revision = '0008074a556d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_complex_aggregations', sa.Column('aggregation_function', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric_complex_aggregations', 'aggregation_function')
    # ### end Alembic commands ###
