"""empty message

Revision ID: b6009fdf88c7
Revises: 95e3e8796193
Create Date: 2017-05-31 15:15:48.852805

"""

# revision identifiers, used by Alembic.
revision = 'b6009fdf88c7'
down_revision = '95e3e8796193'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_column_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sql_metrics', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sql_metrics', 'table_column_groups', ['group_id'], ['id'])
    op.add_column('table_columns', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'table_columns', 'table_column_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table_columns', type_='foreignkey')
    op.drop_column('table_columns', 'group_id')
    op.drop_constraint(None, 'sql_metrics', type_='foreignkey')
    op.drop_column('sql_metrics', 'group_id')
    op.drop_table('table_column_groups')
    # ### end Alembic commands ###
