"""empty message

Revision ID: c08345b06cc8
Revises: 54d08342dc99
Create Date: 2019-02-18 15:57:57.532587

"""

# revision identifiers, used by Alembic.
revision = 'c08345b06cc8'
down_revision = '54d08342dc99'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_filter_settings_dashboard_id_fkey', 'user_filter_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_filter_settings', 'dashboards', ['dashboard_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_filter_settings', type_='foreignkey')
    op.create_foreign_key('user_filter_settings_dashboard_id_fkey', 'user_filter_settings', 'dashboards', ['dashboard_id'], ['id'])
    # ### end Alembic commands ###
