"""empty message

Revision ID: d82b28aab0da
Revises: 3c69c267851b
Create Date: 2020-06-17 12:11:56.033603

"""

# revision identifiers, used by Alembic.
revision = 'd82b28aab0da'
down_revision = '3c69c267851b'

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - ADJUSTED ###
    op.drop_constraint('change_logs_table_id_fkey', 'change_logs', type_='foreignkey')
    op.create_foreign_key(None, 'change_logs', 'tables', ['table_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - ADJUSTED ###
    op.drop_constraint(None, 'change_logs', type_='foreignkey')
    op.create_foreign_key('change_logs_table_id_fkey', 'change_logs', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###
