"""add parent_id in SqlaTable model

Revision ID: e8e3eb006b7c
Revises: c08345b06cc8
Create Date: 2019-07-31 13:57:55.314779

"""

# revision identifiers, used by Alembic.
revision = 'e8e3eb006b7c'
down_revision = 'c08345b06cc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('parent_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'tables', 'tables', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_column('tables', 'parent_id')
    # ### end Alembic commands ###
