"""empty message

Revision ID: f196a24b3886
Revises: b6009fdf88c7
Create Date: 2017-06-04 18:53:06.759089

"""

# revision identifiers, used by Alembic.
revision = 'f196a24b3886'
down_revision = 'b6009fdf88c7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_complex_aggregations', sa.Column('order_columns', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric_complex_aggregations', 'order_columns')
    # ### end Alembic commands ###
