DENIED = 'denied'
CAN_ADD = 'can_add'
CAN_SHOW = 'can_show'
CAN_EXPLORE = 'can_explore'
CAN_EDIT = 'can_edit'
CAN_CONFIG = 'can_config'
CAN_DASHBOARD = 'can_dashboard'
CAN_EXPORT = 'can_export'
CAN_FAVSTAR = 'can_favstar'
CAN_FORCE_UPDATE = 'can_force_update'
CAN_DOWNLOAD = 'can_download'
CAN_DOWNLOAD_CHANGELOG = 'can_download_changelog'
CAN_SAVE_DASH = 'can_save_dash'
CAN_DELETE = 'can_delete'
SCHEMA_ACCESS = 'schema_access'
DATABASE_ACCESS = 'database_access'
DATASOURCE_ACCESS = 'datasource_access'

CAN_LIST = 'can_list'
MULDELETE = 'can_muldelete'
MULTIEXPORT = 'can_mulexport'
REFRESH = 'can_refresh'
YAML_EXPORT = 'can_yaml_export'

BASE_PERMISSIONS = [
    CAN_SHOW,
    CAN_EDIT,
    CAN_CONFIG,
    CAN_DELETE,
    DENIED,
]

EXTRA_PERMISSIONS = [
    CAN_FAVSTAR,
    CAN_FORCE_UPDATE,
    CAN_DOWNLOAD,
]

BASE_OBJECT_PERMISSIONS = BASE_PERMISSIONS + EXTRA_PERMISSIONS

SLICE_PERMISSIONS = BASE_OBJECT_PERMISSIONS + [
    CAN_EXPLORE,
]

DASHBOARD_PERMISSIONS = BASE_OBJECT_PERMISSIONS + [
    CAN_DASHBOARD,
    CAN_SAVE_DASH
]

SLICE_DASH_PERMISSIONS = [
    CAN_EDIT,
    CAN_DOWNLOAD,
    CAN_CONFIG,
    CAN_EXPLORE
]

SQTABLE_PERMISSIONS = BASE_PERMISSIONS + [
    SCHEMA_ACCESS,
    DATASOURCE_ACCESS,
    CAN_EXPLORE
]

DATABASE_PERMISSIONS = BASE_PERMISSIONS + [
    DATABASE_ACCESS,
]

SLICE_MODEL_VIEW_BASE_PERMISSIONS = [
    CAN_ADD,
    CAN_DELETE,
    CAN_EDIT,
    CAN_SHOW,
    CAN_DOWNLOAD,
    CAN_LIST,
    MULDELETE,
    CAN_CONFIG,
]

DASHBOARD_MODEL_VIEW_BASE_PERMISSIONS = [
    CAN_ADD,
    CAN_DASHBOARD,
    CAN_FAVSTAR,
    CAN_FORCE_UPDATE,
    CAN_SAVE_DASH,
    CAN_DELETE,
    CAN_EDIT,
    CAN_SHOW,
    CAN_DOWNLOAD,
    CAN_LIST,
    MULDELETE,
    CAN_CONFIG,
    MULTIEXPORT,
]

TABLE_MODEL_VIEW_BASE_PERMISSIONS = [
    CAN_ADD,
    CAN_EXPLORE,
    CAN_DELETE,
    DATASOURCE_ACCESS,
    CAN_LIST,
    MULDELETE,
    REFRESH,
    YAML_EXPORT,
    CAN_DELETE,
    CAN_EDIT,
    CAN_SHOW,
    CAN_CONFIG,
    CAN_DOWNLOAD_CHANGELOG,
]
